# Generated by Django 4.0 on 2022-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonim', max_length=80),
        ),
        migrations.AlterField(
            model_name='confession',
            name='author',
            field=models.CharField(default='Anonim', max_length=80),
        ),
    ]
