# Generated by Django 4.0 on 2022-12-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_remove_comment_name_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
