# Generated by Django 4.0 on 2022-12-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0003_alter_comment_user_alter_confession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='confession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confession.confession'),
        ),
    ]
