# Generated by Django 4.0 on 2022-12-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0005_comment_approved_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='confession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
